logLevel: info
logDestinations: [stdout]

authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
      - action: api
      - action: metrics

rtmp: true
rtmpAddress: :1935

api: true
apiAddress: :9997

hls: true
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsAlwaysRemux: true
hlsVariant: mpegts
hlsSegmentCount: 7
hlsSegmentDuration: 1s

metrics: true
metricsAddress: :9998

pathDefaults:
  source: publisher

paths:
  all_others:
